<?php
wp_set_current_user(1);
global $checks; $checks=array();function check_ppt($name,$pass,$detail=''){global $checks;$checks[]=array('test'=>$name,'status'=>$pass?'PASS':'FAIL','detail'=>$detail);}
$before=count(get_posts(array('post_type'=>ppt_content_types(),'post_status'=>'publish','numberposts'=>-1)));PPT_Demo_Importer::import_all();$after=count(get_posts(array('post_type'=>ppt_content_types(),'post_status'=>'publish','numberposts'=>-1)));check_ppt('Repeated demo import creates no duplicate posts',$before===$after,"$before / $after");
$pages_before=wp_count_posts('page')->publish;$setup=PPT_Site_Setup::run();check_ppt('Setup repeats without duplicate pages',!is_wp_error($setup)&&$pages_before===wp_count_posts('page')->publish);
$about=get_page_by_path('about');$original=$about->post_content;wp_update_post(array('ID'=>$about->ID,'post_content'=>'QA sentinel genuine editorial revision'));PPT_Site_Setup::run();check_ppt('Setup preserves edited page content',get_post($about->ID)->post_content==='QA sentinel genuine editorial revision');wp_update_post(array('ID'=>$about->ID,'post_content'=>$original));
$article=get_posts(array('post_type'=>'ppt_article','numberposts'=>1))[0];$original_title=$article->post_title;wp_update_post(array('ID'=>$article->ID,'post_title'=>$original_title.' — edited'));$result=PPT_Demo_Importer::remove_all();check_ppt('Removal preserves edited demo record',get_post_status($article->ID)==='publish');check_ppt('Removal preserves real page',get_post_status($about->ID)==='publish');check_ppt('Removal trashes unchanged demo records',$result['trashed']>=60,wp_json_encode($result));
foreach(get_posts(array('post_type'=>ppt_content_types(),'post_status'=>'trash','numberposts'=>-1,'meta_key'=>'_ppt_demo_content','meta_value'=>'1'))as $p){wp_untrash_post($p->ID);wp_update_post(array('ID'=>$p->ID,'post_status'=>'publish'));delete_post_meta($p->ID,'_wp_trash_meta_status');delete_post_meta($p->ID,'_wp_trash_meta_time');update_post_meta($p->ID,'_ppt_demo_fingerprint',PPT_Demo_Importer::fingerprint($p->ID));}
wp_update_post(array('ID'=>$article->ID,'post_title'=>$original_title));update_post_meta($article->ID,'_ppt_demo_fingerprint',PPT_Demo_Importer::fingerprint($article->ID));
$physical=wc_get_product(wc_get_product_id_by_sku('PPT-DEMO-1'));$ebook=wc_get_product(wc_get_product_id_by_sku('PPT-DEMO-4'));$free=wc_get_product(wc_get_product_id_by_sku('PPT-DEMO-11'));
check_ppt('Physical inventory and shipping',$physical->needs_shipping()&&$physical->managing_stock()&&$physical->get_stock_quantity()>0);
check_ppt('Ebook is virtual/downloadable with actual file',$ebook->is_virtual()&&$ebook->is_downloadable()&&count($ebook->get_downloads())===1);
check_ppt('Free resource uses zero price',$free->get_price()==='0');
$order=wc_create_order();$order->set_billing_email('qa@example.test');$order->add_product($ebook,1);$order->calculate_totals();$order->save();
$permissions=WC_Data_Store::load('customer-download')->get_downloads(array('order_id'=>$order->get_id()));check_ppt('Unpaid order has no download permission',count($permissions)===0);
$order->update_status('completed','Local QA only; no payment gateway called.');wc_downloadable_product_permissions($order->get_id(),true);$permissions=WC_Data_Store::load('customer-download')->get_downloads(array('order_id'=>$order->get_id()));check_ppt('Completed test order grants Woo download permission',count($permissions)>0);
$stock=$physical->get_stock_quantity();$stockorder=wc_create_order();$stockorder->add_product($physical,2);$stockorder->calculate_totals();$stockorder->save();wc_reduce_stock_levels($stockorder->get_id());$physical=wc_get_product($physical->get_id());check_ppt('Order reduces physical stock by quantity',$physical->get_stock_quantity()===$stock-2);wc_increase_stock_levels($stockorder->get_id());check_ppt('Stock restores when released',wc_get_product($physical->get_id())->get_stock_quantity()===$stock);
update_option('ppt_enquiry_email','qa@example.test');update_option('ppt_enquiries_enabled',1);update_option('woocommerce_file_download_method','force');update_option('woocommerce_currency','GBP');update_option('woocommerce_default_country','GB');
update_option('woocommerce_bacs_settings',array('enabled'=>'yes','title'=>'Test bank transfer','description'=>'Local QA only. No payment required.'));
$zone=new WC_Shipping_Zone(0);$methods=$zone->get_shipping_methods();if(!$methods){$instance=$zone->add_shipping_method('flat_rate');update_option('woocommerce_flat_rate_'.$instance.'_settings',array('enabled'=>'yes','title'=>'QA flat shipping','cost'=>'4'));}
check_ppt('Core page content is nonempty',count(array_filter($setup,function($id){return trim(get_post($id)->post_content)==='';}))===0);
$download=reset($ebook->get_downloads());file_put_contents(dirname(ABSPATH,3).'/runtime/commerce-fixtures.json',wp_json_encode(array('physical'=>$physical->get_id(),'ebook'=>$ebook->get_id(),'free'=>$free->get_id(),'download'=>$download->get_file(),'order'=>$order->get_id())));
file_put_contents(dirname(ABSPATH,3).'/runtime/integration-results.json',wp_json_encode($checks,JSON_PRETTY_PRINT));echo wp_json_encode($checks,JSON_PRETTY_PRINT);


