<?php
/** Editable launch copy, inserted only into missing pages. */
defined('ABSPATH') || exit;
$copy=array(
'home'=>array('Home','Knowledge for People. Progress for Planet.'),
'about'=>array('About','People & Planet Thrive connects research, publishing and learning with practical action. We are building a place where researchers, practitioners and communities can develop questions together, share evidence and learn from its use.','Why we exist','Useful knowledge needs more than a place to be published. It needs context, open discussion and pathways into decisions. Our launch programme brings scholarly journals, books, practical resources and professional learning into one connected platform.'),
'mission-vision'=>array('Mission & Vision','Our mission is to connect knowledge with practical progress for people and planet.','Our vision','A world where evidence is understandable, learning is accessible and communities can participate in the decisions that affect their future.'),
'our-approach'=>array('Our Approach','We start with a clear question and the people affected by it. Research, publication, learning and collaboration are connected stages of the same work.','Knowledge into practice','Define the problem together. Choose methods appropriate to the question. Explain the limits of the evidence. Publish clearly. Create opportunities to learn, apply and review what follows.'),
'leadership'=>array('Leadership','Leadership information will be published when appointments and public biographies are confirmed.','Working principles','Our intended approach values transparent decisions, responsible stewardship and constructive scrutiny. Enquiries about organisational development can be made through the collaboration form.'),
'careers'=>array('Careers','We welcome interest from people working across research, publishing, learning and operations. No vacancies are currently advertised on this page.','Express your interest','Tell us about your field, the contribution you would like to make and your availability. An expression of interest is not an employment offer.'),
'contact'=>array('Contact','Tell us what you would like to discuss. Choose the relevant enquiry category so your message includes the right context.'),
'work-with-us'=>array('Work With Us','Connect your questions, experience and ideas with a programme that brings research, publishing and learning together.'),
'for-authors'=>array('For Authors','We welcome enquiries about original scholarly work, books and practical knowledge resources. Before sending a proposal, identify its audience, contribution and intended format.','Preparing a proposal','Include a working title, short summary, proposed structure and relevant experience. Explain what is new, how evidence was gathered and any permissions needed. An enquiry does not imply acceptance or a publication contract.'),
'submit-manuscript'=>array('Submit Manuscript','Start with a publishing enquiry describing your manuscript and intended audience. The editorial team can then advise on scope and the appropriate submission route.','Before submission','Prepare an abstract, authorship and contribution statement, funding and conflict disclosures, and a summary of ethics approval where applicable. Do not send confidential participant data through this form.'),
'editorial-policies'=>array('Editorial Policies','Editorial decisions should be grounded in relevance, clarity, integrity and the quality of evidence. Journal-specific processes will be stated before submissions are invited.','Editorial independence','Authors should receive clear information about assessment, revision and decisions. Commercial arrangements must not be presented as a guarantee of editorial acceptance.'),
'publication-ethics'=>array('Publication Ethics','Authors are expected to submit original work, credit contributions accurately and disclose relevant funding and competing interests.','Responsible reporting','Research involving people, animals or sensitive data requires appropriate ethical consideration. Describe consent, approvals and limitations where relevant. Concerns about integrity may be raised through the publishing enquiry form.'),
'peer-review-policy'=>array('Peer Review Policy','Peer review arrangements must be explained for each journal or publication before submission. This page does not imply that demonstration articles have undergone review.','Assessment principles','Reviewers should have relevant expertise, declare conflicts and protect unpublished material. Authors should address feedback clearly. The applicable review model and appeal process will accompany each active publishing programme.'),
'open-access-policy'=>array('Open Access Policy','Access and reuse conditions are specified for each publication. Free access does not automatically grant permission to redistribute or adapt a work.','Licences and charges','Check the licence on the publication itself. Any publication charges or author fees must be disclosed before agreement. No fees or open-access commitments should be inferred from demonstration records.'),
'corrections-retractions'=>array('Corrections & Retractions','Readers and authors can raise concerns about published material through a publishing enquiry. Include the title, location of the concern and supporting evidence.','Maintaining the record','Confirmed errors should be addressed through a visible correction or other appropriate notice. Substantial reliability or integrity issues may require withdrawal or retraction with a clear explanation.'),
'conflicts-of-interest'=>array('Conflicts of Interest','Authors, editors and reviewers should disclose financial, professional and personal interests that could influence the work or its assessment.','Managing disclosures','A disclosed interest is assessed in context. Where independent judgement may be compromised, reassignment or additional oversight may be appropriate. Include relevant disclosures with a proposal or manuscript.'),
'privacy-policy'=>array('Privacy Policy','Use the enquiry form only for information needed to respond to your request. Avoid sensitive personal information and confidential research data.','Launch privacy notice','Contact messages are sent to the configured site recipient. Orders and accounts, when enabled, are processed by WooCommerce and the selected service providers. The operator must publish its confirmed identity, retention periods, lawful basis, processor details and rights contact before accepting live enquiries or orders.'),
 'terms'=>array('Terms & Conditions','Content is provided for information and learning. Publication-specific licences govern reuse; please check the relevant record before sharing or adapting material.','Before purchasing','Read the product description, format, price and delivery terms. Demonstration products are for testing and are not a promise of publication or supply. The operator must approve applicable sales, cancellation, refund and digital-content terms before live commerce begins.'),
'accessibility'=>array('Accessibility','We aim to make research, publications and learning usable with keyboards, assistive technologies and a range of screen sizes.','Report a barrier','Use the contact form to describe the page, what you tried to do and the difficulty you experienced. Please include the browser or assistive technology if you are comfortable sharing it. Accessible alternatives can be discussed for individual resources.'),
'research'=>array('Research','Our research programme connects questions across people, communities and the environment. Explore developing areas and clearly labelled demonstration project concepts.'),
'insights'=>array('Insights','Ideas, analysis and perspectives connecting evidence with action.')
);
$pages=array();
foreach($copy as $slug=>$data){
 $html='<!-- wp:paragraph {"className":"ppt-big-copy"} --><p class="ppt-big-copy">'.esc_html($data[1]).'</p><!-- /wp:paragraph -->';
 if(isset($data[2])) $html.='<!-- wp:heading --><h2 class="wp-block-heading">'.esc_html($data[2]).'</h2><!-- /wp:heading --><!-- wp:paragraph --><p>'.esc_html($data[3]).'</p><!-- /wp:paragraph -->';
 if(in_array($slug,array('contact','careers','submit-manuscript'),true)) $html.='<!-- wp:shortcode -->[ppt_enquiry]<!-- /wp:shortcode -->';
 if($slug==='research') $html.='<!-- wp:shortcode -->[ppt_directory type="ppt_research_area"] [ppt_directory type="ppt_research_project"]<!-- /wp:shortcode -->';
 if($slug==='work-with-us'){
  $paths=array('Publish with us'=>array('Publishing','Authors and editors','Develop a journal article, book or practical resource. Share your audience, outline and proposed contribution so we can discuss editorial fit.'),'Research with us'=>array('Research','Researchers and practitioners','Develop questions and methods around shared challenges. Tell us the question, context and kind of collaboration you seek.'),'Partner with us'=>array('Partnership','Organisations and communities','Explore a shared programme or knowledge exchange. Describe the purpose, participants and resources you could contribute.'),'Train with us'=>array('Training','Trainers and organisations','Develop a practical learning programme. Share your expertise or the needs of your team and preferred delivery mode.'),'Learn with us'=>array('Training','Learners and professional teams','Explore suitable learning opportunities. Tell us your interests, experience and access needs.'),'Write & contribute'=>array('Media','Writers and subject specialists','Propose a clear, evidence-informed insight. Send a short pitch, intended readership and the sources you plan to draw on.'));
  foreach($paths as $title=>$path) $html.='<h2>'.esc_html($title).'</h2><p><strong>'.esc_html($path[1]).'</strong></p><p>'.esc_html($path[2]).'</p><p><a href="'.esc_url(add_query_arg('enquiry',$path[0],home_url('/contact/'))).'">Discuss this pathway →</a></p>';
 }
 $pages[$slug]=array($data[0],$html);
}
return $pages;
